export enum Department {
  Business = '경영학과',
  Economics = '경제통상학과',
  Police = '경찰학과',
  Fire = '소방 방제학과',
  Library = '문헌정보학과',
  Child = '유아교육과',
  Social = '사회복지학과',
  MassCommunication = '신문방송학과',
  Korean = '동화한국어문화학과',
  English = '영어문화학과',
  Mechatronics = '메카트로닉스공학과',
  Computer = '컴퓨터공학과',
  Biomedical = '바이오메디컬공학과',
  GreenTech = '녹색기술융합학과',
  Energy = '에너지신소재공학과',
  Nursing = '간호학과',
  Medicinal = '바이오의약학과',
  BioTech = '생명공학과',
  Food = '식품영양학과',
  Beauty = '뷰티화장품학과',
  Sport = '스포츠건강학과',
  golf = '골프산업학과',
  premedical = '의예과',
}
