export enum Mbti {
  INFP = 'INFP',
  ENFP = 'ENFP',
  INFJ = 'INFJ',
  ENFJ = 'ENFJ',
  INTJ = 'INTJ',
  ENTJ = 'ENTJ',
  INTP = 'INTP',
  ENTP = 'ENTP',
  ISFP = 'ISFP',
  ESFP = 'ESFP',
  ISTP = 'ISTP',
  ESTP = 'ESTP',
  ISFJ = 'ISFJ',
  ESFJ = 'ESFJ',
  ISTJ = 'ISTJ',
  ESTJ = 'ESTJ',
}
