#kummate-be/.github/workflows/deploy.yml
name: Backend CI/CD

on:
  push:
    branches:
      - master  # 또는 배포 브랜치명

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3

      - name: Docker 로그인
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker 이미지 빌드
        run: |
          docker build -t sweeetpotatooo/kummate-backend:${{ github.sha }} .

      - name: Docker 이미지 푸시
        run: |
          docker push sweeetpotatooo/kummate-backend:${{ github.sha }}

      - name: 최신 이미지에 태그 추가
        run: |
          docker tag sweeetpotatooo/kummate-backend:${{ github.sha }} sweeetpotatooo/kummate-backend:latest
          docker push sweeetpotatooo/kummate-backend:latest
